[versions]
# Core toolchain
kotlin = "2.3.10"
compose = "1.10.0"
compose-material3 = "1.11.0-alpha02"
coroutines = "1.10.2"
serialization = "1.10.0"

# Build & tooling
shadow = "9.3.1"
buildConfig = "6.0.7"
ktlint = "14.0.1"
proguard = "7.8.2"
licenseReport = "3.0.1"

# UI & Compose ecosystem
colorPicker = "0.7.0"
fileKit = "0.12.0"
materialKolor = "4.1.1"
navigation-compose = "2.9.1"
reorderable = "3.0.0"
autolinktext = "2.0.2"
shimmer = "1.3.3"
compose-materialIconsExtended = "1.7.3"

# Networking
ktor = "3.4.0"

# Logging
kotlin-logging = "7.0.14"
log4j = "2.25.3"

# System / native
jna = "5.18.1"
oshi = "6.9.3"
themeDetector = "3.9.1"
composeNativeTray = "1.1.0"

# Minecraft
nbt = "6.1"
mcUtils = "3.6.11"

[libraries]
# Core language/runtime
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm", version.ref = "serialization" }
kotlinx-serialization-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlinx-coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }

# UI & Compose ecosystem
autolinktext = { module = "sh.calvin.autolinktext:autolinktext", version.ref = "autolinktext" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
composeShimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
color-picker = { module = "com.godaddy.android.colorpicker:compose-color-picker-jvm", version.ref = "colorPicker" }
reorderable-jvm = { module = "sh.calvin.reorderable:reorderable-jvm", version.ref = "reorderable" }
file-kit = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "fileKit" }
composeNativeTray = { module = "io.github.kdroidfilter:composenativetray", version.ref = "composeNativeTray" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-material3" }
compose-materialIconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "compose-materialIconsExtended" }
compose-desktop-jvm-windows-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-x64", version.ref = "compose" }
compose-desktop-jvm-windows-arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-windows-arm64", version.ref = "compose" }
compose-desktop-jvm-linux-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-x64", version.ref = "compose" }
compose-desktop-jvm-linux-arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-linux-arm64", version.ref = "compose" }
compose-desktop-jvm-macos-x64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-x64", version.ref = "compose" }
compose-desktop-jvm-macos-arm64 = { module = "org.jetbrains.compose.desktop:desktop-jvm-macos-arm64", version.ref = "compose" }

# Networking
ktor-client-core-jvm = { module = "io.ktor:ktor-client-core-jvm", version.ref = "ktor" }
ktor-client-cio-jvm = { module = "io.ktor:ktor-client-cio-jvm", version.ref = "ktor" }
ktor-client-mock-jvm = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktor" }

# Logging
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }

# System / native
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }
theme-detector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "themeDetector" }

# Minecraft
nbt = { module = "com.github.Querz:NBT", version.ref = "nbt" }
mcUtils = { module = "tech.aliorpse.mcutils:mcutils-server-status", version.ref = "mcUtils" }

[plugins]
# Kotlin toolchain
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Compose & build tooling
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dependencyLicenseReport = { id = "com.github.jk1.dependency-license-report", version.ref = "licenseReport" }
